var icons = [
	// version 4.7.0
{className:'all'},
{className:'cart'},
{className:'set'},
{className:'viewgallery'},
{className:'viewlist'},
{className:'attachment'},
{className:'lights'},
{className:'pin'},
{className:'history'},
{className:'move'},
{className:'raw'},
{className:'assessedbadge'},
{className:'remind'},
{className:'canyin'},
{className:'jingdian'},
{className:'zhusu'},
{className:'duanxin'},
{className:'xiangqu'},
{className:'canting'},
{className:'daohang'},
{className:'dizhi'},
{className:'duoyuyan'},
{className:'feiji'},
{className:'fuzhi'},
{className:'gongjiaoche'},
{className:'guanbi'},
{className:'huoche'},
{className:'huobiduihuan'},
{className:'jianshen'},
{className:'kongdiao'},
{className:'mudedi'},
{className:'shijian'},
{className:'shoucang'},
{className:'jiesuo'},
{className:'wuxianwangluo'},
{className:'xiangji'},
{className:'xiangqu1'},
{className:'xingcheng'},
{className:'youji'},
{className:'listview'},
{className:'xiyiji'},
{className:'24xiaoshiqiantai'},
{className:'tupian'},
{className:'gouwu'},
{className:'haitan'},
{className:'huwai'},
{className:'jichengche'},
{className:'jincou'},
{className:'langman'},
{className:'lunchuan'},
{className:'qinzi'},
{className:'renwen'},
{className:'shanchu'},
{className:'shezhi'},
{className:'shengqian'},
{className:'shizhong'},
{className:'shouji'},
{className:'sousuo'},
{className:'tianqi'},
{className:'tupian1'},
{className:'xitongcaidan'},
{className:'xitongfanhui'},
{className:'youxian'},
{className:'yule'},
{className:'zhinengyouhua'},
{className:'zhongzhuan'},
{className:'ziranfengguang'},
{className:'zixingche'},
{className:'zonghe'},
{className:'fenxiang'},
{className:'pinglun'},
{className:'bianji'},
{className:'qifei'},
{className:'jiangluo'},
{className:'xitongfanhui1'},
{className:'buxing'},
{className:'chaping'},
{className:'haoping'},
{className:'shouye'},
{className:'tixing'},
{className:'duogouwu'},
{className:'shaogouwu'},
{className:'dangdi'},
{className:'dixiaofei'},
{className:'gaoxiaofei'},
{className:'jianyuede'},
{className:'jingjide'},
{className:'shushide'},
{className:'gaoduande'},
{className:'shehuade'},
{className:'jinnang'},
{className:'matou'},
{className:'suoding'},
{className:'wancan'},
{className:'wucan'},
{className:'zaocan'},
{className:'zhuyi'},
{className:'baoxue'},
{className:'baoyu'},
{className:'duoyun'},
{className:'leidian'},
{className:'qing'},
{className:'xiaoxue'},
{className:'xiaoyu'},
{className:'yin'},
{className:'zhenxue'},
{className:'zhenyu'},
{className:'zhongxue'},
{className:'zhongyu'},
{className:'qita'},
{className:'fanhui'},
{className:'bingbao'},
{className:'feng'},
{className:'mai'},
{className:'wu'},
{className:'yuxue'},
{className:'safari'},
{className:'zans'},
{className:'yanzhengma'},
{className:'hot'},
{className:'color'},
{className:'originalimage'},
{className:'guanbijiantou'},
{className:'xiaoxi'},
{className:'kuaitui'},
{className:'kuaijin'},
{className:'saoyisao'},
{className:'shuaxin'},
{className:'faxian'},
{className:'lvyouquan'},
{className:'BAI-zuojiantou'},
{className:'BAI-shangjiantou '},
{className:'BAI-youjiantou'},
{className:'BAI-xiajiantou'},
{className:'BAI-qiehuan'},
{className:'biaoqian-pingjia'},
{className:'yifahuo'},
{className:'genggaishouhuodizhi'},
{className:'wangwangcuifu'},
{className:'dianhua1'},
{className:'duanxin1'},
{className:'sousuo1'},
{className:'xin'},
{className:'tuandui'},
{className:'dengta'},
{className:'viphuiyuanhuangguan'},
{className:'huru'},
{className:'dianhua'},
{className:'huchu'},
{className:'changyongshili'},
{className:'erweima'},
{className:'quanping'},
{className:'erweima1'},
{className:'fasong'},
{className:'sucai'},
];

$.expr[':'].icon = function(a, i, m) {
	return (a.getAttribute('data-icon') || '').toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
};
var $container = $('#container_sui_icon');
$.each(icons, function(i, v) {
    var html = ['<div class="card icon-card" style="width:100%"><i class="icon iconfont icon-' + v.className + '"></i><div class="card-body"><p class="card-text">' + v.className + '</p><a href="#" class="btn btn-primary copy-icon-button" data-clipboard-text="' + v.className + '">Copy</a>\
    </div>\
  </div>']
	//var html = [ '<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-2"><div class="card svg-icon-card"><i class="icon iconfont icon-' + v.className + '"></i></div>', '<div>' + v.className + '<span></div>',  '</span>', '</div>', '</li>' ];
	$('<li class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 icon-list"></li>').attr('data-icon', v.className).html(html.join('')).appendTo($container);
});
var $search = $('#search');
$search.on('keyup', function() {
	var filter = $(this).val();
	if (filter) {
		var $matches = $($container).find('li:icon(' + filter + ')');
		$('li', $container).not($matches).hide();
		$matches.show();
	} else {
		$('li', $container).show();
	}

	return false;
});
var clipboard = new ClipboardJS('.copy-icon-button');
$('.copy-icon-button').on("click",function(){
  var iconName = $(this).attr("data-clipboard-text");
  Lobibox.notify('success', {
    size: 'mini',
    title: 'Icon Class Copied',
    sound:false,
    msg: iconName,
    });
})