var icons = [
	// version 2.1.6
	{className:'ad',countryName:'Andorra'},
{className:'ae',countryName:'United Arab Emirates'},
{className:'af',countryName:'Afghanistan'},
{className:'ag',countryName:'Antigua and Barbuda'},
{className:'ai',countryName:'Anguilla'},
{className:'al',countryName:'Albania'},
{className:'am',countryName:'Armenia'},
{className:'ao',countryName:'Angola'},
{className:'aq',countryName:'Antarctica'},
{className:'ar',countryName:'Argentina'},
{className:'as',countryName:'American Samoa'},
{className:'at',countryName:'Austria'},
{className:'au',countryName:'Australia'},
{className:'aw',countryName:'Aruba'},
{className:'ax',countryName:'Åland Islands'},
{className:'az',countryName:'Azerbaijan'},
{className:'ba',countryName:'Bosnia and Herzegovina'},
{className:'bb',countryName:'Barbados'},
{className:'bd',countryName:'Bangladesh'},
{className:'be',countryName:'Belgium'},
{className:'bf',countryName:'Burkina Faso'},
{className:'bg',countryName:'Bulgaria'},
{className:'bh',countryName:'Bahrain'},
{className:'bi',countryName:'Burundi'},
{className:'bj',countryName:'Benin'},
{className:'bl',countryName:'Saint Barthélemy'},
{className:'bm',countryName:'Bermuda'},
{className:'bn',countryName:'Brunei Darussalam'},
{className:'bo',countryName:'Bolivia'},
{className:'bq',countryName:'Bonaire'},
{className:'br',countryName:'Brazil'},
{className:'bs',countryName:'Bahamas'},
{className:'bt',countryName:'Bhutan'},
{className:'bv',countryName:'Bouvet Island'},
{className:'bw',countryName:'Botswana'},
{className:'by',countryName:'Belarus'},
{className:'bz',countryName:'Belize'},
{className:'ca',countryName:'Canada'},
{className:'cc',countryName:'Cocos (Keeling) Islands'},
{className:'cd',countryName:'Congo, the Democratic Republic of the'},
{className:'cf',countryName:'Central African Republic'},
{className:'cg',countryName:'Congo'},
{className:'ch',countryName:'Switzerland'},
{className:'ci',countryName:'Côte dIvoire'},
{className:'ck',countryName:'Cook Islands'},
{className:'cl',countryName:'Chile'},
{className:'cm',countryName:'Cameroon'},
{className:'cn',countryName:'China'},
{className:'co',countryName:'Colombia'},
{className:'cr',countryName:'Costa Rica'},
{className:'cu',countryName:'Cuba'},
{className:'cv',countryName:'Cape Verde'},
{className:'cw',countryName:'Curaçao'},
{className:'cx',countryName:'Christmas Island'},
{className:'cy',countryName:'Cyprus'},
{className:'cz',countryName:'Czech Republic'},
{className:'de',countryName:'Germany'},
{className:'dj',countryName:'Djibouti'},
{className:'dk',countryName:'Denmark'},
{className:'dm',countryName:'Dominica'},
{className:'do',countryName:'Dominican Republic'},
{className:'dz',countryName:'Algeria'},
{className:'ec',countryName:'Ecuador'},
{className:'ee',countryName:'Estonia'},
{className:'eg',countryName:'Egypt'},
{className:'eh',countryName:'Western Sahara'},
{className:'er',countryName:'Eritrea'},
{className:'es-ct',countryName:'Catalonia'},
{className:'es',countryName:'Spain'},
{className:'et',countryName:'Ethiopia'},
{className:'eu',countryName:'European Union'},
{className:'fi',countryName:'Finland'},
{className:'fj',countryName:'Fiji'},
{className:'fk',countryName:'Falkland Islands (Malvinas)'},
{className:'fm',countryName:'Micronesia, Federated States of'},
{className:'fo',countryName:'Faroe Islands'},
{className:'fr',countryName:'France'},
{className:'ga',countryName:'Gabon'},
{className:'gb-eng',countryName:'Saint Georges Cross'},
{className:'gb-nir',countryName:'Northern Ireland'},
{className:'gb-sct',countryName:'Scotland'},
{className:'gb-wls',countryName:'Wales'},
{className:'gb',countryName:'United Kingdom'},
{className:'gd',countryName:'Grenada'},
{className:'ge',countryName:'Georgia'},
{className:'gf',countryName:'French Guiana'},
{className:'gg',countryName:'Guernsey'},
{className:'gh',countryName:'Ghana'},
{className:'gi',countryName:'Gibraltar'},
{className:'gl',countryName:'Greenland'},
{className:'gm',countryName:'Gambia'},
{className:'gn',countryName:'Guinea'},
{className:'gp',countryName:'Guadeloupe'},
{className:'gq',countryName:'Equatorial Guinea'},
{className:'gr',countryName:'Greece'},
{className:'gs',countryName:'South Georgia and the South Sandwich Islands'},
{className:'gt',countryName:'Guatemala'},
{className:'gu',countryName:'Guam'},
{className:'gw',countryName:'Guinea-Bissau'},
{className:'gy',countryName:'Guyana'},
{className:'hk',countryName:'Hong Kong'},
{className:'hm',countryName:'Heard Island and McDonald Islands'},
{className:'hn',countryName:'Honduras'},
{className:'hr',countryName:'Croatia'},
{className:'ht',countryName:'Haiti'},
{className:'hu',countryName:'Hungary'},
{className:'id',countryName:'Indonesia'},
{className:'ie',countryName:'Ireland'},
{className:'il',countryName:'Israel'},
{className:'im',countryName:'Isle of Man'},
{className:'in',countryName:'India'},
{className:'io',countryName:'British Indian Ocean Territory'},
{className:'iq',countryName:'Iraq'},
{className:'ir',countryName:'Iran, Islamic Republic of'},
{className:'is',countryName:'Iceland'},
{className:'it',countryName:'Italy'},
{className:'je',countryName:'Jersey'},
{className:'jm',countryName:'Jamaica'},
{className:'jo',countryName:'Jordan'},
{className:'jp',countryName:'Japan'},
{className:'ke',countryName:'Kenya'},
{className:'kg',countryName:'Kyrgyzstan'},
{className:'kh',countryName:'Cambodia'},
{className:'ki',countryName:'Kiribati'},
{className:'km',countryName:'Comoros'},
{className:'kn',countryName:'Saint Kitts and Nevis'},
{className:'kp',countryName:'Korea, Democratic Peoples Republic of'},
{className:'kr',countryName:'Korea, Republic of'},
{className:'kw',countryName:'Kuwait'},
{className:'ky',countryName:'Cayman Islands'},
{className:'kz',countryName:'Kazakhstan'},
{className:'la',countryName:'Lao Peoples Democratic Republic'},
{className:'lb',countryName:'Lebanon'},
{className:'lc',countryName:'Saint Lucia'},
{className:'li',countryName:'Liechtenstein'},
{className:'lk',countryName:'Sri Lanka'},
{className:'lr',countryName:'Liberia'},
{className:'ls',countryName:'Lesotho'},
{className:'lt',countryName:'Lithuania'},
{className:'lu',countryName:'Luxembourg'},
{className:'lv',countryName:'Latvia'},
{className:'ly',countryName:'Libya'},
{className:'ma',countryName:'Morocco'},
{className:'mc',countryName:'Monaco'},
{className:'md',countryName:'Moldova, Republic of'},
{className:'me',countryName:'Montenegro'},
{className:'mf',countryName:'Saint Martin (French part)'},
{className:'mg',countryName:'Madagascar'},
{className:'mh',countryName:'Marshall Islands'},
{className:'mk',countryName:'Macedonia, the Former Yugoslav Republic of'},
{className:'ml',countryName:'Mali'},
{className:'mm',countryName:'Myanmar'},
{className:'mn',countryName:'Mongolia'},
{className:'mo',countryName:'Macao'},
{className:'mp',countryName:'Northern Mariana Islands'},
{className:'mq',countryName:'Martinique'},
{className:'mr',countryName:'Mauritania'},
{className:'ms',countryName:'Montserrat'},
{className:'mt',countryName:'Malta'},
{className:'mu',countryName:'Mauritius'},
{className:'mv',countryName:'Maldives'},
{className:'mw',countryName:'Malawi'},
{className:'mx',countryName:'Mexico'},
{className:'my',countryName:'Malaysia'},
{className:'mz',countryName:'Mozambique'},
{className:'na',countryName:'Namibia'},
{className:'nc',countryName:'New Caledonia'},
{className:'ne',countryName:'Niger'},
{className:'nf',countryName:'Norfolk Island'},
{className:'ng',countryName:'Nigeria'},
{className:'ni',countryName:'Nicaragua'},
{className:'nl',countryName:'Netherlands'},
{className:'no',countryName:'Norway'},
{className:'np',countryName:'Nepal'},
{className:'nr',countryName:'Nauru'},
{className:'nu',countryName:'Niue'},
{className:'nz',countryName:'New Zealand'},
{className:'om',countryName:'Oman'},
{className:'pa',countryName:'Panama'},
{className:'pe',countryName:'Peru'},
{className:'pf',countryName:'French Polynesia'},
{className:'pg',countryName:'Papua New Guinea'},
{className:'ph',countryName:'Philippines'},
{className:'pk',countryName:'Pakistan'},
{className:'pl',countryName:'Poland'},
{className:'pm',countryName:'Saint Pierre and Miquelon'},
{className:'pn',countryName:'Pitcairn'},
{className:'pr',countryName:'Puerto Rico	'},
{className:'ps',countryName:'Palestine, State of'},
{className:'pt',countryName:'Portugal'},
{className:'pw',countryName:'Palau'},
{className:'py',countryName:'Paraguay'},
{className:'qa',countryName:'Qatar'},
{className:'re',countryName:'Réunion'},
{className:'ro',countryName:'Romania'},
{className:'rs',countryName:'Serbia'},
{className:'ru',countryName:'Russian Federation'},
{className:'rw',countryName:'Rwanda'},
{className:'sa',countryName:'Saudi Arabia'},
{className:'sb',countryName:'Solomon Islands'},
{className:'sc',countryName:'Seychelles'},
{className:'sd',countryName:'Sudan'},
{className:'se',countryName:'Sweden'},
{className:'sg',countryName:'Singapore'},
{className:'sh',countryName:'Saint Helena, Ascension and Tristan da Cunha'},
{className:'si',countryName:'Slovenia'},
{className:'sj',countryName:'Svalbard and Jan Mayen'},
{className:'sk',countryName:'Slovakia'},
{className:'sl',countryName:'Sierra Leone'},
{className:'sm',countryName:'San Marino'},
{className:'sn',countryName:'Senegal'},
{className:'so',countryName:'Somalia'},
{className:'sr',countryName:'Suriname'},
{className:'ss',countryName:'South Sudan'},
{className:'st',countryName:'Sao Tome and Principe'},
{className:'sv',countryName:'El Salvador'},
{className:'sx',countryName:'Sint Maarten (Dutch part)'},
{className:'sy',countryName:'Syrian Arab Republic'},
{className:'sz',countryName:'Swaziland'},
{className:'tc',countryName:'Turks and Caicos Islands'},
{className:'td',countryName:'Chad'},
{className:'tf',countryName:'French Southern Territories'},
{className:'tg',countryName:'Togo'},
{className:'th',countryName:'Thailand'},
{className:'tj',countryName:'Tajikistan'},
{className:'tk',countryName:'Tokelau'},
{className:'tl',countryName:'Timor-Leste'},
{className:'tm',countryName:'Turkmenistan'},
{className:'tn',countryName:'Tunisia'},
{className:'to',countryName:'Tonga'},
{className:'tr',countryName:'Turkey'},
{className:'tt',countryName:'Trinidad and Tobago'},
{className:'tv',countryName:'Tuvalu'},
{className:'tw',countryName:'Taiwan, Province of China'},
{className:'tz',countryName:'Tanzania, United Republic of'},
{className:'ua',countryName:'Ukraine'},
{className:'ug',countryName:'Uganda'},
{className:'um',countryName:'United States Minor Outlying Islands'},
{className:'un',countryName:'United Nations'},
{className:'us',countryName:'United States'},
{className:'uy',countryName:'Uruguay'},
{className:'uz',countryName:'Uzbekistan'},
{className:'va',countryName:'Holy See (Vatican City State)'},
{className:'vc',countryName:'Saint Vincent and the Grenadines'},
{className:'ve',countryName:'Venezuela, Bolivarian Republic of'},
{className:'vg',countryName:'Virgin Islands, British'},
{className:'vi',countryName:'Virgin Islands, U.S.'},
{className:'vn',countryName:'Viet Nam'},
{className:'vu',countryName:'Vanuatu'},
{className:'wf',countryName:'Wallis and Futuna'},
{className:'ws',countryName:'Samoa'},
{className:'ye',countryName:'Yemen'},
{className:'yt',countryName:'Mayotte'},
{className:'za',countryName:'South Africa'},
{className:'zm',countryName:'Zambia'},
{className:'zw',countryName:'Zimbabwe'},
];

$.expr[':'].icon = function(a, i, m) {
	return (a.getAttribute('data-icon') || '').toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
};
var $container = $('#container_sui_icon');
$.each(icons, function(i, v) {
    var html = ['<div class="card icon-card" style="width:100%"><span class="flag-icon flag-icon-' + v.className + '"></span><div class="card-body"><p class="card-text">' + v.countryName + '</p><a href="#" class="btn btn-primary copy-icon-button" data-clipboard-text="' + v.className + '">Copy</a>\
    </div>\
  </div>']
	//var html = [ '<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-2"><div class="card svg-icon-card"><i class="icon iconfont icon-' + v.className + '"></i></div>', '<div>' + v.className + '<span></div>',  '</span>', '</div>', '</li>' ];
	$('<li class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 icon-list"></li>').attr('data-icon', v.countryName).html(html.join('')).appendTo($container);
});
var $search = $('#search');
$search.on('keyup', function() {
	var filter = $(this).val();
	if (filter) {
		var $matches = $($container).find('li:icon(' + filter + ')');
		$('li', $container).not($matches).hide();
		$matches.show();
	} else {
		$('li', $container).show();
	}

	return false;
});
var clipboard = new ClipboardJS('.copy-icon-button');
$('.copy-icon-button').on("click",function(){
  var iconName = $(this).attr("data-clipboard-text");
  Lobibox.notify('success', {
    size: 'mini',
    title: 'Icon Class Copied',
    sound:false,
    msg: iconName,
    });
})