var icons = [
    // version 4.7.0
//City Icons
{className:'#icon-aifeiertieta'},
{className:'#icon-dabenzhong'},
{className:'#icon-dibaifanchuanjiudian'},
{className:'#icon-dongfangmingzhu'},
{className:'#icon-batenongshenmiao'},
{className:'#icon-fuhuojiedao'},
{className:'#icon-fushishan'},
{className:'#icon-jushizhen'},
{className:'#icon-jinzita'},
{className:'#icon-liyuejiduxiang'},
{className:'#icon-kaixuanmen'},
{className:'#icon-ribenshenshe'},
{className:'#icon-bisaxieta'},
{className:'#icon-luomajingjichang'},
{className:'#icon-xinigejuyuan'},
{className:'#icon-taijiling'},
{className:'#icon-shishenrenmianxiang'},
{className:'#icon-changcheng'},
{className:'#icon-ziyounvshenxiang'},
{className:'#icon-ziyuan'},
{className:'#icon-ziyuan1'},
{className:'#icon-ziyuan2'},
{className:'#icon-ziyuan3'},
{className:'#icon-ziyuan4'},
{className:'#icon-ziyuan5'},
{className:'#icon-ziyuan6'},
{className:'#icon-ziyuan7'},
{className:'#icon-ziyuan8'},
{className:'#icon-ziyuan9'},
{className:'#icon-ziyuan10'},
{className:'#icon-ziyuan11'},
{className:'#icon-ziyuan12'},
{className:'#icon-ziyuan13'},
{className:'#icon-ziyuan14'},
{className:'#icon-ziyuan15'},
{className:'#icon-ziyuan16'},
{className:'#icon-ziyuan17'},
{className:'#icon-ziyuan18'},
{className:'#icon-ziyuan19'},
{className:'#icon-ziyuan20'},
{className:'#icon-ziyuan21'},
{className:'#icon-ziyuan22'},
{className:'#icon-ziyuan23'},

//Animal Icons
{className:'#icon-lion'},
{className:'#icon-bull'},
{className:'#icon-hippo'},
{className:'#icon-frog'},
{className:'#icon-panda'},
{className:'#icon-owl'},
{className:'#icon-sheep'},
{className:'#icon-chicken'},
{className:'#icon-duck'},
{className:'#icon-bear'},
{className:'#icon-dog'},
{className:'#icon-tiger'},
{className:'#icon-sea-lion'},
{className:'#icon-cat'},
{className:'#icon-monkey'},
{className:'#icon-elephant'},
{className:'#icon-pig'},
{className:'#icon-alligator'},
{className:'#icon-snake'},
{className:'#icon-mouse'},
{className:'#icon-donkey'},
{className:'#icon-deer'},
{className:'#icon-horse'},
{className:'#icon-seal'},
{className:'#icon-rabbit'},
{className:'#icon-Artboard'},
{className:'#icon-Artboard1'},
{className:'#icon-Artboard2'},
{className:'#icon-Artboard3'},
{className:'#icon-Artboard4'},
{className:'#icon-Artboard5'},
{className:'#icon-Artboard6'},
{className:'#icon-Artboard7'},
{className:'#icon-Artboard8'},
{className:'#icon-Artboard9'},
{className:'#icon-Artboard10'},
{className:'#icon-Artboard11'},
{className:'#icon-Artboard12'},
{className:'#icon-Artboard13'},
{className:'#icon-Artboard14'},
{className:'#icon-Artboard15'},
{className:'#icon-Artboard16'},
{className:'#icon-Artboard17'},
{className:'#icon-Artboard18'},
{className:'#icon-Artboard19'},
{className:'#icon-Artboard20'},
{className:'#icon-Artboard21'},
{className:'#icon-Artboard22'},
{className:'#icon-Artboard23'},
{className:'#icon-Artboard24'},
{className:'#icon-Artboard25'},
{className:'#icon-Artboard26'},
{className:'#icon-Artboard27'},
{className:'#icon-Artboard28'},
{className:'#icon-Artboard29'},
{className:'#icon-Artboard30'},
{className:'#icon-Artboard31'},
{className:'#icon-Artboard32'},
{className:'#icon-Artboard33'},
{className:'#icon-Artboard34'},
{className:'#icon-Artboard35'},

//Sea Icons
{className:'#icon-shuimu'},
{className:'#icon-haicao'},
{className:'#icon-jiashuitong'},
{className:'#icon-huoshanhu'},
{className:'#icon-haidan'},
{className:'#icon-haixing'},
{className:'#icon-luosi'},
{className:'#icon-pangxie'},
{className:'#icon-shanhu'},
{className:'#icon-shuibeng'},
{className:'#icon-shuicao'},
{className:'#icon-yugang'},
{className:'#icon-tupaopao'},
{className:'#icon-yuqun'},
{className:'#icon-wugui'},
{className:'#icon-yusiliao'},
{className:'#icon-yuanxingyugang'},
{className:'#icon-yudou'},
{className:'#icon-xianzhuanghaicao'},
{className:'#icon-bianyu'},

//Travel Icons
{className:'#icon-feiji1'},
{className:'#icon-haixing'},
{className:'#icon-bijini'},
{className:'#icon-jiaopu'},
{className:'#icon-fanchuan'},
{className:'#icon-qianbao1'},
{className:'#icon-shatong'},
{className:'#icon-xiangji1'},
{className:'#icon-shoutixiang'},
{className:'#icon-hanglixiang1'},
{className:'#icon-tuoxie'},
{className:'#icon-zhilupai'},
{className:'#icon-zhangpeng1'},
{className:'#icon-zihangche'},
{className:'#icon-zhinanzhen'},
{className:'#icon-youyongquan'},
{className:'#icon-reqiqiu1'},
{className:'#icon-qianshuijing'},
{className:'#icon-maozi1'},
{className:'#icon-lanche'},
{className:'#icon-ditu'},
{className:'#icon-hanglixiang'},
{className:'#icon-xiangji'},
{className:'#icon-feiji'},
{className:'#icon-zhangpeng'},
{className:'#icon-beibao'},
{className:'#icon-chuifengtong'},
{className:'#icon-lupai'},
{className:'#icon-suishenting'},
{className:'#icon-reqiqiu'},
{className:'#icon-yundongxie'},
{className:'#icon-qianbao'},
{className:'#icon-gaotie'},
{className:'#icon-huoche'},
{className:'#icon-renzituo'},
{className:'#icon-tianqi'},
{className:'#icon-yongyi'},
{className:'#icon-mojing'},
{className:'#icon-mingxinpian'},
{className:'#icon-maozi'},

//Weather Icons
{className:'#icon-yueliang'},
{className:'#icon-taiyang'},
{className:'#icon-qingtian1'},
{className:'#icon-manyue'},
{className:'#icon-Group'},
{className:'#icon-shaoyun'},
{className:'#icon-canyue'},
{className:'#icon-baoyu4'},
{className:'#icon-dayu4'},
{className:'#icon-baoxue4'},
{className:'#icon-daxue4'},
{className:'#icon-dayuzhuanqing'},
{className:'#icon-duoyunzhuanqingtian'},
{className:'#icon-leizhenyu4'},
{className:'#icon-emeiyue'},
{className:'#icon-shandian'},
{className:'#icon-shangxianyue'},
{className:'#icon-wanduoyun'},
{className:'#icon-wanqingtian'},
{className:'#icon-wumai1'},
{className:'#icon-wu2'},
{className:'#icon-tedazhenyu'},
{className:'#icon-xiaxianyue'},
{className:'#icon-xiaoxue3'},
{className:'#icon-xiaoyu3'},
{className:'#icon-xinyue'},
{className:'#icon-yintian1'},
{className:'#icon-zhenyu3'},
{className:'#icon-zhenyuzhuanqing'},
{className:'#icon-yujiaxue3'},
{className:'#icon-zhongxue3'},
{className:'#icon-zhongyu3'},
{className:'#icon-zhangxianyue'},
{className:'#icon-qing1'},


];

$.expr[':'].icon = function(a, i, m) {
	return (a.getAttribute('data-icon') || '').toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
};
var $container = $('#container_sui_icon');
$.each(icons, function(i, v) {
    var html = ['<div class="card icon-card" style="width:100%"><svg aria-hidden="true"><use xlink:href="' + v.className + '"></use></svg><div class="card-body"><p class="card-text">' + v.className + '</p><a href="#" class="btn btn-primary copy-icon-button" data-clipboard-text="' + v.className + '">Copy</a>\
    </div>\
  </div>']
	//var html = [ '<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-2"><div class="card svg-icon-card"><i class="icon iconfont icon-' + v.className + '"></i></div>', '<div>' + v.className + '<span></div>',  '</span>', '</div>', '</li>' ];
	$('<li class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 icon-list"></li>').attr('data-icon', v.className).html(html.join('')).appendTo($container);
});
var $search = $('#search');
$search.on('keyup', function() {
	var filter = $(this).val();
	if (filter) {
		var $matches = $($container).find('li:icon(' + filter + ')');
		$('li', $container).not($matches).hide();
		$matches.show();
	} else {
		$('li', $container).show();
	}

	return false;
});
var clipboard = new ClipboardJS('.copy-icon-button');
$('.copy-icon-button').on("click",function(){
  var iconName = $(this).attr("data-clipboard-text");
  Lobibox.notify('success', {
    size: 'mini',
    title: 'Icon Class Copied',
    sound:false,
    msg: iconName,
    });
})